openapi: 3.0.3
info:
  title: WalletNode REST API
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /artworks/download:
    get:
      tags:
      - artworks
      summary: Returns list of tasks
      description: List of all tasks.
      operationId: artworks#downloadTasks
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadTaskResponseTinyCollection'
              example:
              - file:
                - 68
                - 111
                - 108
                - 111
                - 114
                - 101
                - 32
                - 118
                - 111
                - 108
                - 117
                - 112
                - 116
                - 97
                - 116
                - 101
                - 109
                - 32
                - 105
                - 108
                - 108
                - 111
                - 32
                - 110
                - 111
                - 98
                - 105
                - 115
                - 32
                - 116
                - 101
                - 109
                - 112
                - 111
                - 114
                - 97
                - 46
                id: n6Qn6TFM
                status: Task Started
              - file:
                - 68
                - 111
                - 108
                - 111
                - 114
                - 101
                - 32
                - 118
                - 111
                - 108
                - 117
                - 112
                - 116
                - 97
                - 116
                - 101
                - 109
                - 32
                - 105
                - 108
                - 108
                - 111
                - 32
                - 110
                - 111
                - 98
                - 105
                - 115
                - 32
                - 116
                - 101
                - 109
                - 112
                - 111
                - 114
                - 97
                - 46
                id: n6Qn6TFM
                status: Task Started
              - file:
                - 68
                - 111
                - 108
                - 111
                - 114
                - 101
                - 32
                - 118
                - 111
                - 108
                - 117
                - 112
                - 116
                - 97
                - 116
                - 101
                - 109
                - 32
                - 105
                - 108
                - 108
                - 111
                - 32
                - 110
                - 111
                - 98
                - 105
                - 115
                - 32
                - 116
                - 101
                - 109
                - 112
                - 111
                - 114
                - 97
                - 46
                id: n6Qn6TFM
                status: Task Started
              - file:
                - 68
                - 111
                - 108
                - 111
                - 114
                - 101
                - 32
                - 118
                - 111
                - 108
                - 117
                - 112
                - 116
                - 97
                - 116
                - 101
                - 109
                - 32
                - 105
                - 108
                - 108
                - 111
                - 32
                - 110
                - 111
                - 98
                - 105
                - 115
                - 32
                - 116
                - 101
                - 109
                - 112
                - 111
                - 114
                - 97
                - 46
                id: n6Qn6TFM
                status: Task Started
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - artworks
      summary: Downloads artwork
      description: Download registered artwork.
      operationId: artworks#download
      parameters:
      - name: txid
        in: query
        description: Art Registration Ticket transaction ID
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Art Registration Ticket transaction ID
          example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
          minLength: 46
          maxLength: 64
        example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - name: pid
        in: query
        description: Owner's PastelID
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Owner's PastelID
          example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          pattern: ^[a-zA-Z0-9]+$
          minLength: 86
          maxLength: 86
        example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadResult'
              example:
                task_id: n6Qn6TFM
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - api_key_header_Authorization: []
  /artworks/download/{taskId}:
    get:
      tags:
      - artworks
      summary: Find task by ID
      description: Returns a single task.
      operationId: artworks#dowloadTask
      parameters:
      - name: taskId
        in: path
        description: Task ID of the download process
        required: true
        schema:
          type: string
          description: Task ID of the download process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        example: n6Qn6TFM
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DowloadTaskResponseBody'
              example:
                file:
                - 76
                - 97
                - 98
                - 111
                - 114
                - 105
                - 111
                - 115
                - 97
                - 109
                - 32
                - 108
                - 97
                - 98
                - 111
                - 114
                - 101
                - 32
                - 98
                - 101
                - 97
                - 116
                - 97
                - 101
                - 32
                - 97
                - 108
                - 105
                - 97
                - 115
                - 32
                - 100
                - 101
                - 98
                - 105
                - 116
                - 105
                - 115
                - 46
                id: n6Qn6TFM
                states:
                - date: 2006-01-02T15:04:05Z07:00
                  status: Task Started
                - date: 2006-01-02T15:04:05Z07:00
                  status: Task Started
                - date: 2006-01-02T15:04:05Z07:00
                  status: Task Started
                status: Task Started
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/download/{taskId}/state:
    get:
      tags:
      - artworks
      summary: Streams state by task ID
      description: Streams the state of the download process.
      operationId: artworks#downloadTaskState
      parameters:
      - name: taskId
        in: path
        description: Task ID of the download process
        required: true
        schema:
          type: string
          description: Task ID of the download process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        example: n6Qn6TFM
      responses:
        "101":
          description: Switching Protocols response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskState'
              example:
                date: 2006-01-02T15:04:05Z07:00
                status: Task Started
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register:
    get:
      tags:
      - artworks
      summary: Returns list of tasks
      description: List of all tasks.
      operationId: artworks#registerTasks
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponseTinyCollection'
              example:
              - id: n6Qn6TFM
                status: Task Started
                ticket:
                  artist_name: Leonardo da Vinci
                  artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
                  artist_pastelid_passphrase: qwerasdf1234
                  artist_website_url: https://www.leonardodavinci.net
                  description: The Mona Lisa is an oil painting by Italian artist,
                    inventor, and writer Leonardo da Vinci. Likely completed in 1506,
                    the piece features a portrait of a seated woman set against an
                    imaginary landscape.
                  issued_copies: 1
                  keywords: Renaissance, sfumato, portrait
                  maximum_fee: 100
                  name: Mona Lisa
                  series_name: Famous artist
                  spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
                  youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
                txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
              - id: n6Qn6TFM
                status: Task Started
                ticket:
                  artist_name: Leonardo da Vinci
                  artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
                  artist_pastelid_passphrase: qwerasdf1234
                  artist_website_url: https://www.leonardodavinci.net
                  description: The Mona Lisa is an oil painting by Italian artist,
                    inventor, and writer Leonardo da Vinci. Likely completed in 1506,
                    the piece features a portrait of a seated woman set against an
                    imaginary landscape.
                  issued_copies: 1
                  keywords: Renaissance, sfumato, portrait
                  maximum_fee: 100
                  name: Mona Lisa
                  series_name: Famous artist
                  spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
                  youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
                txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - artworks
      summary: Registers a new artwork
      description: Runs a new registration process for the new artwork.
      operationId: artworks#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
            example:
              artist_name: Leonardo da Vinci
              artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
              artist_pastelid_passphrase: qwerasdf1234
              artist_website_url: https://www.leonardodavinci.net
              description: The Mona Lisa is an oil painting by Italian artist, inventor,
                and writer Leonardo da Vinci. Likely completed in 1506, the piece
                features a portrait of a seated woman set against an imaginary landscape.
              image_id: VK7mpAqZ
              issued_copies: 1
              keywords: Renaissance, sfumato, portrait
              maximum_fee: 100
              name: Mona Lisa
              series_name: Famous artist
              spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
              youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResult'
              example:
                task_id: n6Qn6TFM
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register/{taskId}:
    get:
      tags:
      - artworks
      summary: Find task by ID
      description: Returns a single task.
      operationId: artworks#registerTask
      parameters:
      - name: taskId
        in: path
        description: Task ID of the registration process
        required: true
        schema:
          type: string
          description: Task ID of the registration process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        example: n6Qn6TFM
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterTaskResponseBody'
              example:
                id: n6Qn6TFM
                states:
                - date: 2006-01-02T15:04:05Z07:00
                  status: Task Started
                - date: 2006-01-02T15:04:05Z07:00
                  status: Task Started
                - date: 2006-01-02T15:04:05Z07:00
                  status: Task Started
                status: Task Started
                ticket:
                  artist_name: Leonardo da Vinci
                  artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
                  artist_pastelid_passphrase: qwerasdf1234
                  artist_website_url: https://www.leonardodavinci.net
                  description: The Mona Lisa is an oil painting by Italian artist,
                    inventor, and writer Leonardo da Vinci. Likely completed in 1506,
                    the piece features a portrait of a seated woman set against an
                    imaginary landscape.
                  issued_copies: 1
                  keywords: Renaissance, sfumato, portrait
                  maximum_fee: 100
                  name: Mona Lisa
                  series_name: Famous artist
                  spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
                  youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
                txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register/{taskId}/state:
    get:
      tags:
      - artworks
      summary: Streams state by task ID
      description: Streams the state of the registration process.
      operationId: artworks#registerTaskState
      parameters:
      - name: taskId
        in: path
        description: Task ID of the registration process
        required: true
        schema:
          type: string
          description: Task ID of the registration process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        example: n6Qn6TFM
      responses:
        "101":
          description: Switching Protocols response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskState'
              example:
                date: 2006-01-02T15:04:05Z07:00
                status: Task Started
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /artworks/register/upload:
    post:
      tags:
      - artworks
      summary: Uploads an image
      description: Upload the image that is used when registering a new artwork.
      operationId: artworks#uploadImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadImageRequestBody'
            example:
              file:
              - 65
              - 117
              - 116
              - 32
              - 100
              - 111
              - 108
              - 111
              - 114
              - 101
              - 115
              - 32
              - 117
              - 116
              - 32
              - 102
              - 117
              - 103
              - 105
              - 116
              - 32
              - 116
              - 101
              - 109
              - 112
              - 111
              - 114
              - 97
              - 32
              - 112
              - 101
              - 114
              - 102
              - 101
              - 114
              - 101
              - 110
              - 100
              - 105
              - 115
              - 32
              - 100
              - 111
              - 108
              - 111
              - 114
              - 105
              - 98
              - 117
              - 115
              - 46
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
              example:
                expires_in: 2006-01-02T15:04:05Z07:00
                image_id: VK7mpAqZ
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    ArtworkTicket:
      type: object
      properties:
        artist_name:
          type: string
          description: Name of the artist
          example: Leonardo da Vinci
          maxLength: 256
        artist_pastelid:
          type: string
          description: Artist's PastelID
          example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          pattern: ^[a-zA-Z0-9]+$
          minLength: 86
          maxLength: 86
        artist_pastelid_passphrase:
          type: string
          description: Passphrase of the artist's PastelID
          example: qwerasdf1234
        artist_website_url:
          type: string
          description: Artist website URL
          example: https://www.leonardodavinci.net
          maxLength: 256
        description:
          type: string
          description: Description of the artwork
          example: The Mona Lisa is an oil painting by Italian artist, inventor, and
            writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          maxLength: 1024
        issued_copies:
          type: integer
          description: Number of copies issued
          default: 1
          example: 1
          minimum: 1
          maximum: 1000
        keywords:
          type: string
          description: Keywords
          example: Renaissance, sfumato, portrait
          maxLength: 256
        maximum_fee:
          type: number
          description: Used to find a suitable masternode with a fee equal or less
          default: 1
          example: 100
          minimum: 1e-05
        name:
          type: string
          description: Name of the artwork
          example: Mona Lisa
          maxLength: 256
        series_name:
          type: string
          description: Series name
          example: Famous artist
          maxLength: 256
        spendable_address:
          type: string
          description: Spendable address
          example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          pattern: ^[a-zA-Z0-9]+$
          minLength: 35
          maxLength: 35
        youtube_url:
          type: string
          description: Artwork creation video youtube URL
          example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
          maxLength: 128
      description: Ticket of the registration artwork
      example:
        artist_name: Leonardo da Vinci
        artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        artist_pastelid_passphrase: qwerasdf1234
        artist_website_url: https://www.leonardodavinci.net
        description: The Mona Lisa is an oil painting by Italian artist, inventor,
          and writer Leonardo da Vinci. Likely completed in 1506, the piece features
          a portrait of a seated woman set against an imaginary landscape.
        issued_copies: 1
        keywords: Renaissance, sfumato, portrait
        maximum_fee: 100
        name: Mona Lisa
        series_name: Famous artist
        spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      required:
      - artist_name
      - name
      - issued_copies
      - artist_pastelid
      - artist_pastelid_passphrase
      - spendable_address
      - maximum_fee
    DowloadTaskResponseBody:
      type: object
      properties:
        file:
          type: string
          description: File downloaded
          example:
          - 77
          - 105
          - 110
          - 105
          - 109
          - 97
          - 32
          - 101
          - 120
          - 99
          - 101
          - 112
          - 116
          - 117
          - 114
          - 105
          - 46
          format: binary
        id:
          type: string
          description: JOb ID of the downloading process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        states:
          type: array
          items:
            $ref: '#/components/schemas/TaskState'
          description: List of states from the very beginning of the process
          example:
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
        status:
          type: string
          description: Status of the downloading process
          example: Task Started
          enum:
          - Task Started
          - Connected
          - Error Fingerprints Dont Match
          - Task Rejected
          - Task Completed
      description: DowloadTaskResponseBody result type (default view)
      example:
        file:
        - 78
        - 111
        - 115
        - 116
        - 114
        - 117
        - 109
        - 32
        - 109
        - 105
        - 110
        - 117
        - 115
        - 32
        - 110
        - 111
        - 115
        - 116
        - 114
        - 117
        - 109
        - 32
        - 101
        - 97
        - 32
        - 118
        - 101
        - 114
        - 105
        - 116
        - 97
        - 116
        - 105
        - 115
        - 32
        - 115
        - 101
        - 113
        - 117
        - 105
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 116
        - 101
        - 109
        - 46
        id: n6Qn6TFM
        states:
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        status: Task Started
      required:
      - id
      - status
      - file
    DownloadResult:
      type: object
      properties:
        task_id:
          type: string
          description: Task ID of the download process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
      example:
        task_id: n6Qn6TFM
      required:
      - task_id
    DownloadTaskResponseTiny:
      type: object
      properties:
        file:
          type: string
          description: File downloaded
          example:
          - 69
          - 118
          - 101
          - 110
          - 105
          - 101
          - 116
          - 32
          - 97
          - 117
          - 116
          - 32
          - 101
          - 116
          - 32
          - 117
          - 116
          - 32
          - 99
          - 117
          - 109
          - 113
          - 117
          - 101
          - 32
          - 97
          - 109
          - 101
          - 116
          - 32
          - 100
          - 101
          - 98
          - 105
          - 116
          - 105
          - 115
          - 46
          format: binary
        id:
          type: string
          description: JOb ID of the downloading process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        status:
          type: string
          description: Status of the downloading process
          example: Task Started
          enum:
          - Task Started
          - Connected
          - Error Fingerprints Dont Match
          - Task Rejected
          - Task Completed
      description: Image downloaded payload (tiny view)
      example:
        file:
        - 65
        - 112
        - 101
        - 114
        - 105
        - 97
        - 109
        - 32
        - 115
        - 117
        - 115
        - 99
        - 105
        - 112
        - 105
        - 116
        - 32
        - 114
        - 101
        - 114
        - 117
        - 109
        - 46
        id: n6Qn6TFM
        status: Task Started
      required:
      - id
      - status
      - file
    DownloadTaskResponseTinyCollection:
      type: array
      items:
        $ref: '#/components/schemas/DownloadTaskResponseTiny'
      description: DownloadTasksResponseBody is the result type for an array of DownloadTaskResponse
        (tiny view)
      example:
      - file:
        - 68
        - 111
        - 108
        - 111
        - 114
        - 101
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 116
        - 101
        - 109
        - 32
        - 105
        - 108
        - 108
        - 111
        - 32
        - 110
        - 111
        - 98
        - 105
        - 115
        - 32
        - 116
        - 101
        - 109
        - 112
        - 111
        - 114
        - 97
        - 46
        id: n6Qn6TFM
        status: Task Started
      - file:
        - 68
        - 111
        - 108
        - 111
        - 114
        - 101
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 116
        - 101
        - 109
        - 32
        - 105
        - 108
        - 108
        - 111
        - 32
        - 110
        - 111
        - 98
        - 105
        - 115
        - 32
        - 116
        - 101
        - 109
        - 112
        - 111
        - 114
        - 97
        - 46
        id: n6Qn6TFM
        status: Task Started
      - file:
        - 68
        - 111
        - 108
        - 111
        - 114
        - 101
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 116
        - 101
        - 109
        - 32
        - 105
        - 108
        - 108
        - 111
        - 32
        - 110
        - 111
        - 98
        - 105
        - 115
        - 32
        - 116
        - 101
        - 109
        - 112
        - 111
        - 114
        - 97
        - 46
        id: n6Qn6TFM
        status: Task Started
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    Image:
      type: object
      properties:
        expires_in:
          type: string
          description: Image expiration
          example: 2006-01-02T15:04:05Z07:00
          format: date-time
        image_id:
          type: string
          description: Uploaded image ID
          example: VK7mpAqZ
          minLength: 8
          maxLength: 8
      example:
        expires_in: 2006-01-02T15:04:05Z07:00
        image_id: VK7mpAqZ
      required:
      - image_id
      - expires_in
    RegisterRequestBody:
      type: object
      properties:
        artist_name:
          type: string
          description: Name of the artist
          example: Leonardo da Vinci
          maxLength: 256
        artist_pastelid:
          type: string
          description: Artist's PastelID
          example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          pattern: ^[a-zA-Z0-9]+$
          minLength: 86
          maxLength: 86
        artist_pastelid_passphrase:
          type: string
          description: Passphrase of the artist's PastelID
          example: qwerasdf1234
        artist_website_url:
          type: string
          description: Artist website URL
          example: https://www.leonardodavinci.net
          maxLength: 256
        description:
          type: string
          description: Description of the artwork
          example: The Mona Lisa is an oil painting by Italian artist, inventor, and
            writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          maxLength: 1024
        image_id:
          type: string
          description: Uploaded image ID
          example: VK7mpAqZ
          minLength: 8
          maxLength: 8
        issued_copies:
          type: integer
          description: Number of copies issued
          default: 1
          example: 1
          minimum: 1
          maximum: 1000
        keywords:
          type: string
          description: Keywords
          example: Renaissance, sfumato, portrait
          maxLength: 256
        maximum_fee:
          type: number
          description: Used to find a suitable masternode with a fee equal or less
          default: 1
          example: 100
          minimum: 1e-05
        name:
          type: string
          description: Name of the artwork
          example: Mona Lisa
          maxLength: 256
        series_name:
          type: string
          description: Series name
          example: Famous artist
          maxLength: 256
        spendable_address:
          type: string
          description: Spendable address
          example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          pattern: ^[a-zA-Z0-9]+$
          minLength: 35
          maxLength: 35
        youtube_url:
          type: string
          description: Artwork creation video youtube URL
          example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
          maxLength: 128
      example:
        artist_name: Leonardo da Vinci
        artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        artist_pastelid_passphrase: qwerasdf1234
        artist_website_url: https://www.leonardodavinci.net
        description: The Mona Lisa is an oil painting by Italian artist, inventor,
          and writer Leonardo da Vinci. Likely completed in 1506, the piece features
          a portrait of a seated woman set against an imaginary landscape.
        image_id: VK7mpAqZ
        issued_copies: 1
        keywords: Renaissance, sfumato, portrait
        maximum_fee: 100
        name: Mona Lisa
        series_name: Famous artist
        spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      required:
      - image_id
      - artist_name
      - name
      - issued_copies
      - artist_pastelid
      - artist_pastelid_passphrase
      - spendable_address
      - maximum_fee
    RegisterResult:
      type: object
      properties:
        task_id:
          type: string
          description: Task ID of the registration process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
      example:
        task_id: n6Qn6TFM
      required:
      - task_id
    RegisterTaskResponseBody:
      type: object
      properties:
        id:
          type: string
          description: JOb ID of the registration process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        states:
          type: array
          items:
            $ref: '#/components/schemas/TaskState'
          description: List of states from the very beginning of the process
          example:
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
        status:
          type: string
          description: Status of the registration process
          example: Task Started
          enum:
          - Task Started
          - Connected
          - Image Probed
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error Fingerprints Dont Match
          - Task Rejected
          - Task Completed
        ticket:
          $ref: '#/components/schemas/ArtworkTicket'
        txid:
          type: string
          description: txid
          example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
          minLength: 64
          maxLength: 64
      description: RegisterTaskResponseBody result type (default view)
      example:
        id: n6Qn6TFM
        states:
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      required:
      - id
      - status
      - ticket
    TaskResponseTiny:
      type: object
      properties:
        id:
          type: string
          description: JOb ID of the registration process
          example: n6Qn6TFM
          minLength: 8
          maxLength: 8
        status:
          type: string
          description: Status of the registration process
          example: Task Started
          enum:
          - Task Started
          - Connected
          - Image Probed
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error Fingerprints Dont Match
          - Task Rejected
          - Task Completed
        ticket:
          $ref: '#/components/schemas/ArtworkTicket'
        txid:
          type: string
          description: txid
          example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
          minLength: 64
          maxLength: 64
      description: TaskResponse result type (tiny view)
      example:
        id: n6Qn6TFM
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      required:
      - id
      - status
      - ticket
    TaskResponseTinyCollection:
      type: array
      items:
        $ref: '#/components/schemas/TaskResponseTiny'
      description: RegisterTasksResponseBody is the result type for an array of TaskResponse
        (tiny view)
      example:
      - id: n6Qn6TFM
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - id: n6Qn6TFM
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - id: n6Qn6TFM
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - id: n6Qn6TFM
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
    TaskState:
      type: object
      properties:
        date:
          type: string
          description: Date of the status creation
          example: 2006-01-02T15:04:05Z07:00
        status:
          type: string
          description: Status of the registration process
          example: Task Started
          enum:
          - Task Started
          - Connected
          - Image Probed
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error Fingerprints Dont Match
          - Task Rejected
          - Task Completed
      example:
        date: 2006-01-02T15:04:05Z07:00
        status: Task Started
      required:
      - date
      - status
    UploadImageRequestBody:
      type: object
      properties:
        file:
          type: string
          description: File to upload
          example:
          - 76
          - 97
          - 98
          - 111
          - 114
          - 105
          - 111
          - 115
          - 97
          - 109
          - 32
          - 108
          - 105
          - 98
          - 101
          - 114
          - 111
          - 32
          - 116
          - 101
          - 110
          - 101
          - 116
          - 117
          - 114
          - 32
          - 118
          - 105
          - 116
          - 97
          - 101
          - 32
          - 98
          - 108
          - 97
          - 110
          - 100
          - 105
          - 116
          - 105
          - 105
          - 115
          - 32
          - 115
          - 111
          - 108
          - 117
          - 116
          - 97
          - 46
          format: binary
        filename:
          type: string
          description: For internal use
      example:
        file:
        - 85
        - 116
        - 32
        - 101
        - 117
        - 109
        - 32
        - 101
        - 108
        - 105
        - 103
        - 101
        - 110
        - 100
        - 105
        - 32
        - 118
        - 101
        - 108
        - 105
        - 116
        - 32
        - 115
        - 101
        - 113
        - 117
        - 105
        - 32
        - 118
        - 111
        - 108
        - 117
        - 112
        - 116
        - 97
        - 116
        - 101
        - 32
        - 101
        - 97
        - 46
      required:
      - file
  securitySchemes:
    api_key_header_Authorization:
      type: apiKey
      description: Art Owner's passphrase to authenticate
      name: Authorization
      in: header
